import { useQuery } from "@tanstack/react-query";
import type { UseFormReturn } from "react-hook-form";
import { Check, Package } from "lucide-react";
import { Link } from "react-router-dom";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { SearchablePicker } from "@/components/searchable-picker";
import { getInventoryItems } from "@/lib/api";
import { ImageUpload, SettingsField, SettingsPanel } from "./settings-components";
import { brandPresets, paymentOptions, type SettingsFormData, type SettingsSectionId } from "./settings-model";

export function StoreSettingsPanels({ section, form, watched, busy }: { section: SettingsSectionId; form: UseFormReturn<SettingsFormData>; watched: Partial<SettingsFormData>; busy: boolean }) {
  const errors = form.formState.errors;
  const accessibility = (field: keyof SettingsFormData) => ({ "aria-invalid": !!errors[field], "aria-describedby": errors[field] ? `settings-${field}-error` : `settings-${field}-hint` });
  if (section === "business") return <SettingsPanel title="Business details" description="The store identity and contact information used across your workspace." tag="Shared store settings"><div className="settings-form-grid">
    <SettingsField id="settings-storeName" label="Store name" required error={errors.storeName?.message} hint="Shown in your store workspace and documents." className="full"><Input id="settings-storeName" autoComplete="organization" {...form.register("storeName")} {...accessibility("storeName")} /></SettingsField>
    <SettingsField id="settings-storePhone" label="Store phone" error={errors.storePhone?.message} hint="The contact number customers can use."><Input id="settings-storePhone" type="tel" autoComplete="tel" {...form.register("storePhone")} {...accessibility("storePhone")} /></SettingsField>
    <SettingsField id="settings-storeEmail" label="Store email" error={errors.storeEmail?.message} hint="Your business contact email."><Input id="settings-storeEmail" type="email" autoComplete="email" {...form.register("storeEmail")} {...accessibility("storeEmail")} /></SettingsField>
    <SettingsField id="settings-storeAddress" label="Store address" error={errors.storeAddress?.message} className="full"><textarea id="settings-storeAddress" autoComplete="street-address" rows={3} {...form.register("storeAddress")} {...accessibility("storeAddress")} /></SettingsField>
  </div></SettingsPanel>;
  if (section === "sales") return <SettingsPanel title="Invoices & sales" description="Invoice settings and the starting payment method for new sales."><div className="settings-form-grid"><SettingsField id="settings-currency" label="Currency" hint="Bangladeshi Taka is the store currency."><Input id="settings-currency" value={`BDT / ${watched.currencySymbol || "৳"}`} readOnly /></SettingsField><SettingsField id="settings-invoicePrefix" label="Invoice prefix" required hint="Used when a new invoice number is created." error={errors.invoicePrefix?.message}><Input id="settings-invoicePrefix" {...form.register("invoicePrefix")} {...accessibility("invoicePrefix")} /></SettingsField><SettingsField id="settings-defaultPaymentMethod" label="Default payment method" error={errors.defaultPaymentMethod?.message} hint="Preselected for a new sale; you can change it during checkout." className="full"><SearchablePicker triggerId="settings-defaultPaymentMethod" label="Default payment method" placeholder="Choose a method" value={watched.defaultPaymentMethod} options={paymentOptions} purchasePresentation onChange={(value) => form.setValue("defaultPaymentMethod", value as SettingsFormData["defaultPaymentMethod"], { shouldDirty: true, shouldValidate: true })} /></SettingsField></div><div className="settings-info-note"><Check size={16} aria-hidden="true" /><p>Existing invoice numbers and historical sale records retain their saved information.</p></div></SettingsPanel>;
  if (section === "inventory") return <SettingsPanel title="Stock alerts" description="Review a color when its Rolls or Meter reaches either limit." tag="Live preview"><div className="settings-form-grid"><SettingsField id="settings-lowStockRollThreshold" label="Rolls review limit" required error={errors.lowStockRollThreshold?.message} hint="A whole number. Colors at or below this limit need review."><div className="settings-unit-input"><Input id="settings-lowStockRollThreshold" type="number" inputMode="numeric" min={0} step={1} {...form.register("lowStockRollThreshold", { valueAsNumber: true })} {...accessibility("lowStockRollThreshold")} /><span>Rolls</span></div></SettingsField><SettingsField id="settings-lowStockMeterThreshold" label="Meter review limit" required error={errors.lowStockMeterThreshold?.message} hint="Colors at or below this Meter limit also need review."><div className="settings-unit-input"><Input id="settings-lowStockMeterThreshold" type="number" inputMode="decimal" min={0} step="any" {...form.register("lowStockMeterThreshold", { valueAsNumber: true })} {...accessibility("lowStockMeterThreshold")} /><span>Meter</span></div></SettingsField></div><StockAlertPreview rolls={watched.lowStockRollThreshold} meter={watched.lowStockMeterThreshold} /><div className="settings-info-note"><Package size={16} aria-hidden="true" /><p>Alert limits help you review inventory. They do not change available Rolls or Meter.</p></div></SettingsPanel>;
  if (section === "appearance") return <SettingsPanel title="Store branding" description="Update your store logo, browser icon and saved brand color."><div className="settings-images-grid"><ImageUpload id="logoUrl" label="Store logo" value={watched.logoUrl} disabled={busy} error={errors.logoUrl?.message} onChange={(value) => form.setValue("logoUrl", value, { shouldDirty: true, shouldValidate: true })} /><ImageUpload id="faviconUrl" label="Browser favicon" value={watched.faviconUrl} disabled={busy} error={errors.faviconUrl?.message} onChange={(value) => form.setValue("faviconUrl", value, { shouldDirty: true, shouldValidate: true })} /></div><div className="settings-accent-section"><SettingsField id="settings-brandAccent" label="Brand color" hint="Saved with your store branding." error={errors.brandAccent?.message}><div className="settings-color-inputs"><input type="color" aria-label="Choose brand color" value={/^#[0-9a-fA-F]{6}$/.test(watched.brandAccent ?? "") ? watched.brandAccent : "#895332"} onChange={(event) => form.setValue("brandAccent", event.target.value, { shouldDirty: true, shouldValidate: true })} /><Input id="settings-brandAccent" {...form.register("brandAccent")} {...accessibility("brandAccent")} spellCheck={false} /></div></SettingsField><div className="settings-color-presets" role="group" aria-label="Brand color presets">{brandPresets.map((preset) => <button type="button" key={preset.color} aria-pressed={watched.brandAccent?.toLowerCase() === preset.color.toLowerCase()} onClick={() => form.setValue("brandAccent", preset.color, { shouldDirty: true, shouldValidate: true })}><i style={{ background: preset.color }} />{preset.label}{watched.brandAccent?.toLowerCase() === preset.color.toLowerCase() && <Check size={12} aria-hidden="true" />}</button>)}</div></div></SettingsPanel>;
  return null;
}

function StockAlertPreview({ rolls, meter }: { rolls?: number; meter?: number }) {
  const stock = useQuery({ queryKey: ["inventory", "settings-preview"], queryFn: () => getInventoryItems(), staleTime: 60000 });
  const valid = typeof rolls === "number" && Number.isInteger(rolls) && rolls >= 0 && typeof meter === "number" && Number.isFinite(meter) && meter >= 0;
  const variants = (stock.data ?? []).flatMap((item) => item.variants);
  const flagged = valid ? variants.filter((variant) => variant.totalRolls <= rolls || variant.totalMeters <= meter).length : 0;
  return <div className="settings-alert-preview"><div><span className="settings-small-label">Current stock · preview</span><h3>{!valid ? "Enter valid limits to preview alerts" : stock.isPending ? "Loading inventory…" : stock.isError ? "Inventory preview unavailable" : variants.length === 0 ? "No inventory to review yet" : <><strong>{flagged}</strong> of {variants.length} color variants would need review</>}</h3><p>{valid && !stock.isPending && !stock.isError ? `${variants.length - flagged} above both limits · Save to apply these alert limits.` : "Uses current inventory and your selected Rolls / Meter limits."}</p></div>{stock.isError ? <Button type="button" variant="outline" disabled={stock.isFetching} onClick={() => void stock.refetch()}>Retry preview</Button> : <Button type="button" variant="outline" asChild><Link to="/inventory">View inventory</Link></Button>}{valid && !stock.isPending && !stock.isError && variants.length > 0 && <div className="settings-alert-bar" role="meter" aria-label="Color variants that would need stock review" aria-valuemin={0} aria-valuemax={variants.length} aria-valuenow={flagged}><span style={{ width: `${flagged / variants.length * 100}%` }} /></div>}</div>;
}
