-- Add activity types without rewriting existing records.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECORD_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECORD_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECORD_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SIGNED_IN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SIGNED_OUT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVOICE_EMAIL_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVOICE_EMAIL_FAILED';
